# Generated by Django 5.1 on 2024-08-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
    ]
