# Generated by Django 5.1 on 2024-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="display_columns",
        ),
        migrations.AddField(
            model_name="organization",
            name="display_columns",
            field=models.JSONField(default=list),
        ),
    ]
