# Generated by Django 5.1 on 2024-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_remove_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="display_columns",
            field=models.JSONField(default=list),
        ),
    ]
