services:
  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: omni_django
    env_file:
      - ../.envs/.django
      - ../.envs/.postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:14
    container_name: omni_postgres
    env_file:
      - ../.envs/.postgres
    ports:
      - "5432:5432"
