#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
exec python manage.py runserver 0.0.0.0:8000

# static to serve with nginx
# python manage.py collectstatic --noinput
# exec gunicorn omni.wsgi --bind 0.0.0.0:8000 --chdir=/app
