#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Activate the Poetry virtual environment
if [ -f ".venv/bin/activate" ]; then
    source .venv/bin/activate
fi

python manage.py migrate
exec python manage.py runserver 0.0.0.0:8000
